config/routes.rb
Rails.application.routes.draw do
  resources :skills
  resources :candidates
  root "home#index"
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get "userindex", to: "users#index", as: "userindex"
  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"
end

app/models/user.rb
class User < ApplicationRecord
  
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    uniqueness: { case_sensitive: false },
                    format: { with: VALID_EMAIL_REGEX }
                    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    redirect_to root_path
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        flash[:notice] = 'User was successfully created.'
        format.html { redirect_to root_url}
        format.json { render :show, status: :created, location: @user }
        format.js { render js: 'window.top.location.reload(true);' }
      else
        format.js { render layout: false, content_type: 'text/javascript' }
        format.html
      end
    end
  end

  # PATCH/PUT /users/1
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /users/1
  def destroy
    if (current_user == @user)
      session[:user_id] = nil
    end
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
    
    def logged_in_user
      unless current_user
        flash[:alert] = "Please log in."
        redirect_to root_url
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user, remote: true) do |f| %>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_new.html.erb
<div>
  <p id="notice"><%= notice %></p>
</div>

<% if current_user %>
  <p><b>Logged in as <%= current_user.email %></b></p>
  <%= link_to "View User list", userindex_path %>
  
<% else %>
  <%= render "sessions/new" %>
  <div id="myModal2" class="modal fade" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content text-center">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Enter Details</h4>
        </div>
        <div id = "usererrors"></div>
        <div class="modal-body div-centered">
          <%= render 'users/form', user: @user  %>
        </div>
        <div class="modal-footer">
        </div>
      </div>
    </div>
  </div>
  
<% end %>

app/views/users/edit.html.erb
<div id = "userindex" class="row d-flex justify-content-center">
    <div id = "editusererrors"></div>
        <div class="col-sm-12 h-100 d-table">
            <div class="col-6 align-self-center">
            <h1>Editing User</h1>
            <%= render 'form', user: @user %>
            <%= link_to 'Show', @user %> |
            <%= link_to 'Back', users_path %>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<div id = "userindex" class="row d-flex justify-content-center">
  <div class="col-sm-12 h-100 d-table">
    <div class="col-6 align-self-center">
      <h1>Users</h1>
      
      <table>
        <thead>
          <tr>
            <th>Email</th>
            <th colspan="3"></th>
          </tr>
        </thead>
      
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.email %></td>
              <td><%= link_to 'Show', user %></td>
              <td><%= link_to 'Edit', edit_user_path(user) %></td>
              <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    
      <br>
      <%= link_to 'Home Page', root_url %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div id = "userindex" class="row d-flex justify-content-center">
  <div class="col-sm-12 h-100 d-table">
    <div class="col-6 align-self-center">
      <p id="notice"><%= notice %></p>

      <p>
        <strong>Email:</strong>
        <%= @user.email %>
      </p>
      
      <%= link_to 'Edit', edit_user_path(@user) %> |
      <%= link_to 'Back', users_path %>
    </div>
  </div>
</div>