config/routes.rb
Rails.application.routes.draw do
  resources :skills
  resources :candidates
  root "home#index"
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get "userindex", to: "users#index", as: "userindex"
  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @candidates = Candidate.all
    @skills = Skill.all
    @user = User.new
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_candidateTab.html.erb
<% if current_user %>
  <table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Name</th>
      <th scope="col">Phone number</th>
      <th scope="col">Email</th>
    </tr>
  </thead>
    <tbody>
      <% @candidates.each do |candidate| %>
        <tr>
          <td><%= candidate.id %></td>
          <td><%= candidate.name %></td>
          <td><%= candidate.phone_number %></td>
          <td><%= candidate.email %></td>
          <td><%= link_to 'Show', candidate, remote: true %></td>
          <td><%= link_to 'Edit', edit_candidate_path(candidate),remote: true %></td>
          <td><%= link_to 'Destroy', candidate, method: :delete, data: { confirm: 'Are you sure?' },remote: true %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div id ="candidatemodals"></div>
  
  <button class="btn btn-md btn-primary" type="button" data-toggle="modal" data-target="#myModal">Add Candidate</button>
  
  <div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content text-center">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Add new Candidate</h4>
        </div>
         <div id = "candidateerrors"></div>
        <div class="modal-body div-centered">
          <%= render 'candidates/form', candidate: Candidate.new %>
        </div>
        <div class="modal-footer">
        </div>
      </div>
    </div>
  </div>
<% else %>
  <p> You must login to view Candidates </p>
<% end %>

app/views/home/_error_message.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/home/_loginTab.html.erb
<div>
  <p id="notice"><%= notice %></p>
</div>

<% if current_user %>
  <p><b>Logged in as <%= current_user.email %></b></p>
  <%= link_to "View User list", userindex_path %>
  
<% else %>
  <%= render "sessions/new" %>
  <div id="myModal2" class="modal fade" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content text-center">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Enter Details</h4>
        </div>
        <div id = "usererrors"></div>
        <div class="modal-body div-centered">
          <%= render 'users/form', user: @user  %>
        </div>
        <div class="modal-footer">
        </div>
      </div>
    </div>
  </div>
  
<% end %>

app/views/home/_skillsTab.html.erb
<% if current_user %>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Name</th>
        <th scope="col">Proficiency</th>
        <th scope="col">Description</th>
        <th scope="col">Candidate</th>
      </tr>
    </thead>
    <tbody>
      <% @skills.each do |skill| %>
        <% if @current_skill == skill %>
          <tr class="line-item-highlight">
        <% else %>
          <tr>
        <% end %>
            <td><%= skill.id %></td>
            <td><%= skill.name %></td>
            <td><%= skill.proficiency %></td>
            <td><%= skill.description %></td>
            <td><%= skill.candidate.name %></td>
            <td><%= link_to 'Show', skill, remote: true %></td>
            <td><%= link_to 'Edit', edit_skill_path(skill), remote: true %></td>
            <td><%= link_to 'Destroy', skill, method: :delete, data: { confirm: 'Are you sure?' } ,remote: true %></td>
          </tr>
      <% end %>
    </tbody>
  </table>
  
  <div id ="skillmodals"></div>
  
  <button class="btn btn-md btn-primary" type="button" data-toggle="modal" data-target="#myModal1">Add Skill</button>
  
  <div id="myModal1" class="modal fade" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content text-center">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Add Skill</h4>
        </div>
        <div id = "skillerrors"></div>
        <div class="modal-body div-centered">
          <%= render 'skills/form', skill: Skill.new %>
        </div>
        <div class="modal-footer">
        </div>
      </div>
    </div>
  </div>
                
<% else %>
  <p> You must login to view Skills </p>
<% end %>

app/views/home/index.html.erb
<% if current_user %>
  <div id = "logout"> <%= link_to "Log Out", logout_path %> </div>
<% end %>
<div class="container" style="border:1px solid #cecece;">
  <div class="clearfix">
    <%= image_tag("book.png",class:"float-left", :alt => "book icon") %>
    <h1 id ="recruit"> Recruit - Educators </h1> 
  </div>

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" id="myTab" role="tablist" >
    <li class="nav-item active">
      <a class="nav-link" id="login-tab" data-toggle="tab" href="#login" role="tab" aria-controls="login" aria-selected="true">Login</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="candidates-tab" data-toggle="tab" href="#candidates" role="tab" aria-controls="candidates" aria-selected="false">Candidates</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="skills-tab" data-toggle="tab" href="#skillstab1" role="tab" aria-controls="skills" aria-selected="false">Skills</a>
    </li>
  </ul>
  
  <!-- Tab panes -->
  <div class="tab-content" id = "maintable" >
    <div class="tab-pane active text-center" id="login" role="tabpanel" aria-labelledby="login-tab">
      <%= render "users/new" %>
    </div>
  
    <div class="tab-pane" id="candidates" role="tabpanel" aria-labelledby="candidates-tab">
      <div id = "rencandidates">
      <%= render "candidateTab" %>
      </div>
    </div>
    
    <div class="tab-pane" id="skillstab1" role="tabpanel" aria-labelledby="skills-tab">
    <div id = "renskills">
      <%= render "skillsTab" %> 
    </div>
       
    </div>
  </div>
</div>
                
                